[package]
org = "ballerinax"
name = "mssql.cdc.driver"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["CDC", "Debezium", "Microsoft SQL Server", "MSSQL", "Area/Database", "Type/Driver", "Vendor/Red Hat"]
repository = "https://github.com/ballerina-platform/module-ballerinax-mssql.cdc.driver"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.13.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "mssql.cdc.driver-native"
version = "@toml.version@"
path = "../native/build/libs/mssql.cdc.driver-native-@project.version@.jar"

[[platform.java21.dependency]]
groupId = "io.debezium"
artifactId = "debezium-connector-sqlserver"
version = "@debezium.version@"
path = "./lib/debezium-connector-sqlserver-@debezium.version@.jar"
